-- MySQL Script generated by MySQL Workbench
-- 2024年05月18日 星期六 18时02分03秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plane_ticket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `plane_ticket` ;

-- -----------------------------------------------------
-- Schema plane_ticket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plane_ticket` ;
USE `plane_ticket` ;

-- -----------------------------------------------------
-- Table `plane_ticket`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plane_ticket`.`user` ;

CREATE TABLE IF NOT EXISTS `plane_ticket`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `dob` DATE NOT NULL,
  `sex` CHAR(1) NOT NULL,
  `email` VARCHAR(50) NULL,
  `phone` VARCHAR(30) NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `admin_tag` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = ndbcluster;


-- -----------------------------------------------------
-- Table `plane_ticket`.`passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plane_ticket`.`passenger` ;

CREATE TABLE IF NOT EXISTS `plane_ticket`.`passenger` (
  `passenger_id` INT NOT NULL AUTO_INCREMENT,
  `id` CHAR(18) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `mail` VARCHAR(50) NULL,
  `phone` VARCHAR(20) NOT NULL,
  `sex` CHAR(1) NOT NULL,
  `dob` DATE NULL,
  PRIMARY KEY (`passenger_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plane_ticket`.`airplane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plane_ticket`.`airplane` ;

CREATE TABLE IF NOT EXISTS `plane_ticket`.`airplane` (
  `airplane_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  `capacity` SMALLINT NOT NULL,
  `identifier` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`airplane_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plane_ticket`.`airpot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plane_ticket`.`airpot` ;

CREATE TABLE IF NOT EXISTS `plane_ticket`.`airpot` (
  `airpot_id` INT NOT NULL AUTO_INCREMENT,
  `iata` CHAR(3) NOT NULL,
  `icao` CHAR(4) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NULL,
  `country` VARCHAR(50) NULL,
  `latitude` DECIMAL(11,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  PRIMARY KEY (`airpot_id`),
  UNIQUE INDEX `iata_UNIQUE` (`iata` ASC) VISIBLE,
  UNIQUE INDEX `icao_UNIQUE` (`icao` ASC) VISIBLE,
  INDEX `name_index` (`name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'na';


-- -----------------------------------------------------
-- Table `plane_ticket`.`airline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plane_ticket`.`airline` ;

CREATE TABLE IF NOT EXISTS `plane_ticket`.`airline` (
  `airline_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `iata` CHAR(2) NOT NULL,
  `airpot_id` INT NOT NULL,
  PRIMARY KEY (`airline_id`),
  UNIQUE INDEX `iata_UNIQUE` (`iata` ASC) VISIBLE,
  INDEX `fk_airline_airpot1_idx` (`airpot_id` ASC) VISIBLE,
  CONSTRAINT `fk_airline_airpot1`
    FOREIGN KEY (`airpot_id`)
    REFERENCES `plane_ticket`.`airpot` (`airpot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plane_ticket`.`flightschedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plane_ticket`.`flightschedule` ;

CREATE TABLE IF NOT EXISTS `plane_ticket`.`flightschedule` (
  `flight_no` CHAR(8) NOT NULL,
  `departure` TIME NOT NULL,
  `arrival` TIME NOT NULL,
  `duration` SMALLINT NOT NULL,
  `monday` TINYINT NULL DEFAULT 0,
  `tuesday` TINYINT NULL DEFAULT 0,
  `wednesday` TINYINT NULL DEFAULT 0,
  `thursday` TINYINT NULL DEFAULT 0,
  `friday` TINYINT NULL DEFAULT 0,
  `saturday` TINYINT NULL DEFAULT 0,
  `sunday` TINYINT NULL DEFAULT 0,
  `airline_id` INT NOT NULL,
  `from_airport_id` INT NOT NULL,
  `to_airport_id` INT NOT NULL,
  PRIMARY KEY (`flight_no`),
  INDEX `fk_flightschedule_airline1_idx` (`airline_id` ASC) VISIBLE,
  INDEX `fk_flightschedule_airpot1_idx` (`from_airport_id` ASC) VISIBLE,
  INDEX `fk_flightschedule_airpot2_idx` (`to_airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_flightschedule_airline1`
    FOREIGN KEY (`airline_id`)
    REFERENCES `plane_ticket`.`airline` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flightschedule_airpot1`
    FOREIGN KEY (`from_airport_id`)
    REFERENCES `plane_ticket`.`airpot` (`airpot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flightschedule_airpot2`
    FOREIGN KEY (`to_airport_id`)
    REFERENCES `plane_ticket`.`airpot` (`airpot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plane_ticket`.`flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plane_ticket`.`flight` ;

CREATE TABLE IF NOT EXISTS `plane_ticket`.`flight` (
  `flight_id` INT NOT NULL AUTO_INCREMENT,
  `departure` DATETIME NOT NULL,
  `arrival` DATETIME NOT NULL,
  `duration` SMALLINT NOT NULL,
  `airplane_id` INT NOT NULL,
  `airpline_id` INT NOT NULL,
  `flight_no` CHAR(8) NOT NULL,
  `from_airport_id` INT NOT NULL,
  `to_airport_id` INT NOT NULL,
  PRIMARY KEY (`flight_id`),
  INDEX `fk_flight_airplane1_idx` (`airplane_id` ASC) VISIBLE,
  INDEX `fk_flight_airline1_idx` (`airpline_id` ASC) VISIBLE,
  INDEX `fk_flight_flightschedule1_idx` (`flight_no` ASC) VISIBLE,
  INDEX `fk_flight_airpot1_idx` (`from_airport_id` ASC) VISIBLE,
  INDEX `fk_flight_airpot2_idx` (`to_airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_flight_airplane1`
    FOREIGN KEY (`airplane_id`)
    REFERENCES `plane_ticket`.`airplane` (`airplane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_airline1`
    FOREIGN KEY (`airpline_id`)
    REFERENCES `plane_ticket`.`airline` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_flightschedule1`
    FOREIGN KEY (`flight_no`)
    REFERENCES `plane_ticket`.`flightschedule` (`flight_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_airpot1`
    FOREIGN KEY (`from_airport_id`)
    REFERENCES `plane_ticket`.`airpot` (`airpot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_airpot2`
    FOREIGN KEY (`to_airport_id`)
    REFERENCES `plane_ticket`.`airpot` (`airpot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plane_ticket`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plane_ticket`.`ticket` ;

CREATE TABLE IF NOT EXISTS `plane_ticket`.`ticket` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `seat` CHAR(4) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `passenger_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `flight_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_ticket_passenger_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_ticket_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_ticket_flight1_idx` (`flight_id` ASC) VISIBLE,
  CONSTRAINT `purchase`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `plane_ticket`.`passenger` (`passenger_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book for`
    FOREIGN KEY (`user_id`)
    REFERENCES `plane_ticket`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_flight1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `plane_ticket`.`flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
